William/v1 dev
DeCenter-AI/decenterai.com pull request #34
Opened 2023-10-11 17:05 UTC by techyNonso

2023-10-11 17:25 UTC, Nasfame requested changes
rebase with main

2023-10-11 17:32 UTC, techyNonso reviewed
okay

2023-10-11 19:54 UTC, Nasfame requested changes
fix: demo buttons

2023-10-12 05:12 UTC, closed without merging

2023-10-12 05:12 UTC, Nasfame commented
Merged in HEAD