William/remove garbage code of app
DeCenter-AI/decenterai.com pull request #45
Opened 2023-10-16 19:40 UTC by techyNonso

## Related Issue(s)

Fixes #
<br>
For #

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## Screenshots

## To-Do

- [ ]

## Additional Information

2023-10-16 19:50 UTC, techyNonso commented
@Nasfame please review this as soon as possible

2023-10-16 23:04 UTC, Nasfame requested changes

2023-10-16 23:04 UTC, Nasfame commented on src/app/components/home/Hero.tsx
> +            <Link href="https://app.decenterai.com/explore">
just direct to https://app.decenterai.com/

2023-10-16 23:08 UTC, Nasfame requested changes

2023-10-16 23:08 UTC, Nasfame commented on src/app/components/home/Hero.tsx
> +            <Link href="https://app.decenterai.com/explore" className="hidden md:block">
don't do a refactor to https://app.decenterai.com. no explore. We cannot do this all the time,

2023-10-17 23:22 UTC, Nasfame commented on src/app/components/home/Hero.tsx
> +            <Link href="https://app.decenterai.com/explore" className="hidden md:block">
Do a refactor to `https://app.decenterai.com/.` not /explore

2023-10-17 23:22 UTC, Nasfame commented on src/app/components/home/Hero.tsx
> +            <Link href="https://app.decenterai.com/explore" className="hidden md:block">
@techyNonso

2023-10-18 08:32 UTC, Nasfame approved these changes
LGTM: @techyNonso u can merge if thats all the changes

2023-10-18 10:02 UTC, merged